# Generated by Django 2.2.5 on 2019-09-27 23:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tellphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('type', models.CharField(choices=[('home', 'Home'), ('cell', 'Cell'), ('work', 'Work')], max_length=10)),
            ],
        ),
    ]
